### ISSUE TITLE
可以加个配置, 关闭通知通道吗?

### ISSUE THREAD

**Issue by java8site** [OpenMindOpenWorld/aliyun-push-flutter-plugin#10]
推送 ,android 除了阿里自己的通道还有第三方厂商, ios端有阿里自己的通道和apns, 我是想只使用 安卓第三方厂商, 和ios的apns ,想关闭阿里自己的推送通道. 
1. ios处理是, 关闭推送消息通道（长链），需要保证在SDK初始化之前调用, closeCCPChannel
2. android 我看你写的文档, Future<Map<dynamic, dynamic>> turnOffAndroidPushChannel(), 不知道是否也是关闭长连接通道
如果android是关闭长连接通道的话, 那么需要ios加一个closeCCPChannel
大佬可以处理一下, 发个版本嘛?

**Comment by kanata996** [comment]
https://help.aliyun.com/document_detail/2249916.html?spm=a2c4g.2249910.0.0.36eba8f9OTsht8
不能关闭推送通道。查看上面文档，可以设置OpenAPI的SendChannels参数为你想要的通道。生产环境下，有些厂商通道需要去各家手机厂商申请通知通道和模板。
集成厂商通道文档：https://help.aliyun.com/document_detail/434677.html?spm=a2c4g.434676.0.0.56481d2cjUr2Kj#d39101c752tdd

**Comment by kanata996** [comment]
> 大佬可以在把ios的这个closeCCPChannel方法给加到flutter里面嘛? @kanata996

1.2.3版本新增了 iOS closeCCPChannel.

**Comment by java8site** [comment]
🙏多谢
