### ISSUE TITLE
No such module 'AlicloudUtils'

### ISSUE THREAD

**Issue by java8site** [OpenMindOpenWorld/aliyun-push-flutter-plugin#11]
大佬， 我又来了。 ios使用时候，有时候会报错
No such module 'AlicloudUtils'
/Users/wyw/Desktop/workspace/flutter/joy/package/aliyun-push-flutter-plugin-main/ios/Classes/AliyunPushPlugin.swift:0:7

第一次使用时后时也报这个错了，后来莫名好了，
最近我又打包，然后又报这个了

**Comment by java8site** [comment]
找到问题了，[AlicloudPush](https://github.com/aliyun/aliyun-specs/tree/master/Specs/AlicloudPush)插件包，以前版本是2.1.0默认引入了依赖AlicloudUtils， 现在最新版本是2.2.0，里面没有引入依赖AlicloudUtils

https://github.com/aliyun/aliyun-specs/blob/master/Specs/AlicloudPush/2.1.0/AlicloudPush.podspec
https://github.com/aliyun/aliyun-specs/blob/master/Specs/AlicloudPush/2.2.0/AlicloudPush.podspec

以下是2.1.0
Pod::Spec.new do |s|
  s.name         = "AlicloudPush"
  s.version      = "2.1.0"
  s.summary      = "Aliyun Mobile Service Push iOS SDK."
  s.homepage     = "https://www.aliyun.com/product/cps?spm=5176.56115.416540.85.uEfXjX"
  s.author       = { "junmo" => "lingkun.lk@alibaba-inc.com" }

 
  s.source       = { :http => "https://ios-repo.oss-cn-shanghai.aliyuncs.com/push/2.1.0/push.zip" }
  s.vendored_frameworks = 'push/CloudPushSDK.xcframework'

  s.platform     = :ios
  s.ios.deployment_target = '12.0'

  s.frameworks = 'CoreTelephony', 'SystemConfiguration'
  s.libraries = 'sqlite3.0', 'resolv'
  s.xcconfig = { 'OTHER_LDFLAGS' => '$(inherited) -ObjC' }

  s.dependency   "AlicloudUtils"
  s.dependency	 "AlicloudUTDID"


end

**Comment by WFCN** [comment]
所以哥们怎么解决的,不太懂iOS,遇到了同样的问题,感谢感谢

**Comment by java8site** [comment]
> 所以哥们怎么解决的,不太懂iOS,遇到了同样的问题,感谢感谢
你增加个
s.dependency "AlicloudUtils"
s.dependency "AlicloudUTDID"

就行了

**Comment by WFCN** [comment]
好的  谢谢 哥们

**Comment by kanata996** [comment]
周末我修复一下这个问题，并升级一下阿里云最新的Android和iOS的推送SDK版本。抱歉。

**Comment by java8site** [comment]
> 周末我修复一下这个问题，并升级一下阿里云最新的Android和iOS的推送SDK版本。抱歉。

多谢大佬
