### ISSUE TITLE
Android的App被杀死后,走厂商通道收到推送,此时点击通知,可以正常打开app首页,但是收不到onNotificationOpened回调

### ISSUE THREAD

**Issue by WFCN** [OpenMindOpenWorld/aliyun-push-flutter-plugin#16]
如题,请问您有遇到这个问题吗

**Comment by kanata996** [comment]
1. 辅助通道需要使用PushPopupActivity。
2. 收到onNotificationOpened回调的一个原因可能是：App启动时没有来得及调用addPushCallback。你可以启动App后，在控制台用仅厂商通道的方式手动推送一个通知，是可以收到的。

**Comment by WFCN** [comment]
> 1. 辅助通道需要使用PushPopupActivity。
> 2. 收到onNotificationOpened回调的一个原因可能是：App启动时没有来得及调用addPushCallback。你可以启动App后，在控制台用仅厂商通道的方式手动推送一个通知，是可以收到的。


是这种情况,我看PushPopupActivity的代码里是会打开MainActivity,回调onNotificationOpened方法,估计就是此时没有注册addPushCallback导致的,这种情况下,这个回调的时机是不是可以延迟一下

**Comment by kanata996** [comment]
所以你希望怎么做？修改PushPopupActivity？或者，你尝试在 main 里调用addPushCallback，看看是否能解决这个问题。

**Comment by WFCN** [comment]
目前没想到什么解决方案,有时间了研究下,提个pr
