### ISSUE TITLE
大佬你好,请教一下

### ISSUE THREAD

**Issue by java8site** [OpenMindOpenWorld/aliyun-push-flutter-plugin#9]
大佬你好,
我这边想用aliyun_push这个推送, 然后咱这插件因为没有用过, 想先咨询一下ios端真机, 实际效果现在是可以正常稳定使用了嘛?

**Comment by kanata996** [comment]
你好。因为我们之前接入的是阿里云官方的插件，但由于阿里云长期不更新，导致不能使用Flutter新版本。所以我用Kotlin和Swift重写了一个新插件，并新增了一些功能，比如Android辅助弹窗。
目前我们的App已经用这个插件替换阿里云官方插件了，一切正常。替换的过程也很简单，所有API都兼容官方插件API。

**Comment by java8site** [comment]
好的, 多谢大佬 @kanata996
